# Generated by Django 6.1 on 2026-09-09 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('acido_base', 'Ácido-base'), ('redox', 'Redox'), ('complexometrica', 'Complexometrica'), ('precipitacao', 'Precipitação')], max_length=20)),
                ('data_realizacao', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolucaoTitulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('concentracao_nominal', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fator_correcao', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('data_padronizacao', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solucoes_titulantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Titulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_titulante', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume_amostra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('concentracao_calculada', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulacoes', to='titulacoes.experimento')),
                ('solucao_titulante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulacoes', to='titulacoes.solucaotitulante')),
            ],
        ),
    ]
