# Generated by Django 6.1 on 2026-09-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulacao',
            name='coeficiente_analito',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='titulacao',
            name='coeficiente_titulante',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
